export const ROUTES = {
  LOGIN: 'LOGIN',
  RESETPASSWORD: 'RESETPASSWORD',
  EMAILVERIFICATION: 'EMAILVERIFICATION',
  HOME: 'Users',
  INFOFILLING: 'INFOFILLING',
  GROUPS: 'Groups',
  CHAT: 'Chat',
  SETTINGS: 'Settings',

  BASICINFO: 'BASICINFO',
  PREFERENCE: 'PREFERENCE',
};
